CREATE TABLE conversation_states (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_phone VARCHAR(20) NOT NULL,
  current_step VARCHAR(100) NOT NULL,
  temp_data JSON NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);